/* Autogenerated sharedvars for DEADLINE version=0.25.2 branch=release */
export type sharedvars_generated = {
    /** Newest server version */
    api_newest_server_version: string;
    /** Whether staying in the air will kill you */
    ac_airtime_kill: boolean;
    /** Whether momentum is enabled */
    plr_momentum: boolean;
    /** Whether capture zone beam outlines are shown */
    gm_capture_zone_outline: boolean;
    /** How long to wait before hiding magazine stats */
    plr_mag_stats_timeout: number;
    /** How long map voting lasts */
    sv_map_vote_time: number;
    /** Normalized age at which smoke puff starts fading out */
    cfg_smoke_fade_out_start: number;
    /** Maximum allowed player ping */
    plr_ping_limit_sec: number;
    /** Time in seconds before curl noise reaches full strength */
    cfg_smoke_curl_ramp_time: number;
    /** Whether team killing is enabled */
    plr_team_kill: boolean;
    /**  */
    ff_field_voicelines: boolean;
    /** . */
    ac_sound_kill: boolean;
    /** Default radius of voxel destruction */
    voxel_destruction_radius: number;
    /** Color player NVG */
    plr_nv_color: Color3;
    /** max fps limit while dbg_limit_fps is enabled */
    dbg_max_fps: number;
    /** Player vault barrier height reduction. Set dbg_vault_lines to true before playing with these values! */
    plr_vault_barrier_height_reduction: number;
    /** Player viewmodel state transition speed multiplier */
    plr_viewmodel_state_transition_speed: number;
    /** Grenade physics friction */
    plr_grenade_friction: number;
    /** whether shell extraction location is shown */
    dbg_show_shell_location: boolean;
    /** Default grid size for voxel destruction */
    voxel_default_grid_size: number;
    /** The amount of players a team can be unbalanced by before team switching isn't allowed */
    gm_team_balancing_threshold: number;
    /** Minimum buoyancy force for smoke puffs */
    cfg_smoke_buoyancy_min: number;
    /** Radius of voxel destruction from bullet hits */
    voxel_bullet_destruction_radius: number;
    /** Game update message shown to returning players */
    api_update_message: string;
    /** Whether RPG ammo refills are disabled */
    plr_disable_rpg_refill: boolean;
    /** Divisor for remote player look activity in equipment loop volume */
    cfg_equip_loop_remote_look_div: number;
    /** Player explosion damage multiplier */
    plr_explosion_damage_multiplier: number;
    /** VIP server owner */
    readonly vip_owner: string;
    /** Whether Volumika is enabled */
    sv_volumika: boolean;
    /** Tracer bullet size */
    sv_tracer_size: number;
    /** Server timescale. 1 means realtime. Setting this to 0 will break the game */
    sv_timescale: number;
    /** Player headshot damage multiplier */
    plr_headshot_damage_multiplier: number;
    /** Whether explosive projectile arming is disabled, meaning they will explode upon contact immediately */
    plr_disable_arming: boolean;
    /** Maximum chat history */
    chat_max_history: number;
    /** Set to 1 to enable smoke culling debug output */
    cfg_smoke_debug_cull: number;
    /** Server time offset in hours. A value of 1 means 1 hour forwards */
    sv_time_offset: number;
    /** Camera FOV while in freecam */
    plr_freecam_fov: number;
    /** Server sound speed in studs */
    sv_sound_speed: number;
    /** How often set dressing events are triggered */
    sv_set_dressing_events_frequency_hz: number;
    /** Whether set dressing events are enabled. Events include background audio or passing aircraft */
    sv_set_dressing_events_enabled: boolean;
    /** Whether the server uses the map's defined preset when switching maps */
    sv_respect_preset_properties: boolean;
    /** Whether tracers have random colors */
    sv_rainbow_tracers: boolean;
    /** Whether team scrambling is enabled when a match starts */
    gm_team_scrambling: boolean;
    /** Player max directional distance */
    plr_max_directional_distance: number;
    /** whether bot pathfinding lines are enabled */
    dbg_bot_pathfind_lines: boolean;
    /** Player movement smoothing */
    plr_movement_damping: number;
    /** Whether map voting is enabled */
    sv_map_voting: boolean;
    /** Editor hover distance */
    editor_hover_distance: number;
    /** whether Canim animator debug is enabled */
    dbg_canim: boolean;
    /** How long to wait before capturing a point in push */
    gm_push_time_to_capture: number;
    /** How long the intermission between matches lasts */
    sv_map_intermission_time: number;
    /** Player stamina drain while vaulting */
    plr_vault_stamina_drain: number;
    /** Server replication packet size for outgoing player data */
    gm_replication_packet_size_bytes_outgoing: number;
    /** Whether the gun editor is only enabled during intermission */
    sv_intermission_only_editor: boolean;
    /** How long to wait before spawning players in push */
    gm_push_spawn_timer: number;
    /** spawn transition time */
    dbg_spawn_transition_time: number;
    /** Lifetime of a smoke puff in seconds */
    cfg_smoke_puff_lifetime: number;
    /** Player barrel deviation */
    plr_barrel_deviation: number;
    /** Whether PVP is enabled */
    plr_pvp: boolean;
    /** Player shove melee headshot damage */
    plr_shove_melee_headshot_damage: number;
    /** Timeout before invalidating a shot */
    ac_shot_timeout: number;
    /** Server gravity. Mapped to workspace.Gravity */
    sv_gravity: number;
    /** Whether tracers are force enabled */
    sv_force_tracers: boolean;
    /** Whether suppression is enabled */
    plr_suppression: boolean;
    /** Initial velocity of emitted smoke puffs */
    cfg_smoke_emit_force: number;
    /** Whether auto jump is enabled */
    plr_auto_jump: boolean;
    /** Server day cycle speed in seconds. A value of 1 is 1:1 to real life */
    sv_day_cycle_speed: number;
    /** Place configuration. decides whether the server runs as the lobby or main game */
    readonly place_config: string;
    /** Server creation time */
    sv_creation_time: number;
    /** How fast curl noise pattern changes over time */
    cfg_smoke_curl_change_speed: number;
    /** Whether objective markers are enabled */
    gm_objective_markers: boolean;
    /** Whether bots spawn on their own */
    sv_bot_auto_spawning_enabled: boolean;
    /** Divisor for local player camera speed in equipment loop volume */
    cfg_equip_loop_camera_div: number;
    /** Maximum volume for local player equipment loop */
    cfg_equip_loop_max_vol: number;
    /** How much time the player has after spawning to reset to the lobby instantly */
    plr_instant_lobby_return_time: number;
    /** Player vault frontal size x. Set dbg_vault_lines to true before playing with these values! */
    plr_vault_frontal_size_x: number;
    /** whether character controller gizmos are enabled */
    dbg_char_gizmos: boolean;
    /** Player shove bayonet torso damage */
    plr_shove_bayonet_torso_damage: number;
    /** Player shove headshot damage */
    plr_shove_headshot_damage: number;
    /** Player vault barrier distance addition. Set dbg_vault_lines to true before playing with these values! */
    plr_vault_barrier_distance_addition: number;
    /** Normalized age at which smoke puff reaches full opacity */
    cfg_smoke_fade_in_end: number;
    /** Whether the Luau mod console environment was loaded */
    ro_server_console_loaded: boolean;
    /** Game-wide announcement */
    api_announcement: string;
    /** Whether money functions are enabled */
    ro_luau_give_money_enabled: boolean;
    /** Vertical curl noise variance per puff */
    cfg_smoke_curl_y_variance: number;
    /** Whether Staging branch players get money */
    ro_infinite_money_in_staging: boolean;
    /** Whether players without chat roles are kicked from the game */
    ro_kick_non_roled_players: boolean;
    /** Player vault frontal detection length. Set dbg_vault_lines to true before playing with these values! */
    plr_vault_frontal_detection_length: number;
    /** How many points to award per second in other gamemodes */
    gm_points_per_second: number;
    /** Server join message. Set with chat.set_join_message(message) */
    ro_join_message: string;
    /** Whether one hand aiming is enabled. When enabled, the default keybind is I */
    plr_enable_gangsta_control: boolean;
    /** whether fps is limited to dbg_max_fps */
    dbg_limit_fps: boolean;
    /** Player laser max directional distance */
    plr_laser_max_directional_distance: number;
    /** Whether chat is disabled */
    ro_chat_disable: boolean;
    /** Player stamina run drain */
    plr_stamina_run_drain: number;
    /** Whether weapon stats are clamped */
    plr_weapon_clamp_stats_values: boolean;
    /** Maximum volume for remote player equipment loop */
    cfg_equip_loop_remote_max_vol: number;
    /** How long a smoke grenade emits smoke in seconds */
    cfg_smoke_burn_duration: number;
    /** Player vault minimum delay before starting animation */
    plr_vault_min_delay: number;
    /**  */
    dbg_check_for_thread_yielding: boolean;
    /** enables customizing any weapon recoil patterns in the F10 menu */
    dbg_recoil: boolean;
    /** Whether backblast debug is active */
    dbg_backblast: boolean;
    /** Whether ceasefire is enabled */
    plr_ceasefire: boolean;
    /** Whether RemoteEvent profiling is enabled */
    dbg_event_profiling: boolean;
    /** Player vault max delay before starting animation */
    plr_vault_max_delay: number;
    /** Whether aiming in bushes is enabled */
    plr_aim_in_bushes: boolean;
    /** Whether chat announces server changes */
    chat_announce_changes: boolean;
    /** Player max object interaction distance */
    plr_max_interaction_distance: number;
    /** Player vault top check raycast count. Set dbg_vault_lines to true before playing with these values! */
    plr_vault_top_check_raycast_count: number;
    /** Player shove bayonet limb damage */
    plr_shove_bayonet_limb_damage: number;
    /** Whether microprofiler tags are enabled */
    dbg_profiling: boolean;
    /** Geographical server location */
    sv_location: string;
    /** Player vault rotation limit. Set dbg_vault_lines to true before playing with these values! */
    plr_vault_rotation_limit: number;
    /** projectile gizmos */
    dbg_projectile: boolean;
    /** whether warpzone debug is enabled */
    dbg_warpzones: boolean;
    /** Player speed multiplier */
    plr_speed: number;
    /** How close a bot has to be to its target to consider it reached */
    bot_target_reach_distance: number;
    /** ping warning threshold in milliseconds */
    plr_ping_warning_threshold_ms: number;
    /** Maximum buoyancy force for smoke puffs */
    cfg_smoke_buoyancy_max: number;
    /** Smoothing speed for local player equipment loop volume */
    cfg_equip_loop_smooth: number;
    /** How much smoke puffs grow over their lifetime */
    cfg_smoke_puff_growth: number;
    /** Player vault height */
    plr_vault_height: number;
    /** Player vault frontal size y. Set dbg_vault_lines to true before playing with these values! */
    plr_vault_frontal_size_y: number;
    /** Player stamina regen speed while crouching */
    plr_stamina_crouch_regen: number;
    /** Player vault barrier move time multiplier. Set dbg_vault_lines to true before playing with these values! */
    plr_vault_barrier_move_time_multiplier: number;
    /** Player vault barrier initial delay multiplier. Set dbg_vault_lines to true before playing with these values! */
    plr_vault_barrier_initial_delay_multiplier: number;
    /** Reason why spawning is disabled. Set with (set-spawning-disabled-reason reason) */
    ro_spawning_disabled_reason: string;
    /** Player vault barrier detection raycast multiplier. Set dbg_vault_lines to true before playing with these values! */
    plr_vault_barrier_detection_raycast_multiplier: number;
    /** Whether the server is a VIP server */
    readonly is_vip_server: boolean;
    /** Whether the server will handle messages from deadlinegame.com */
    api_messaging_enabled: boolean;
    /** Whether loadout editing is disabled */
    gm_disable_loadout_editing: boolean;
    /** Player swift switch speed multiplier */
    plr_swift_switch_speed_multiplier: number;
    /** Player stamina shake multiplier */
    plr_stamina_shake_multiplier: number;
    /** Player movement stiffness at maximum weight */
    plr_movement_max_stiffness: number;
    /** How long it takes to drown */
    plr_drown_time: number;
    /** Whether markers are enabled */
    plr_enable_markers: boolean;
    /** Grenade physics elasticity (bounciness) */
    plr_grenade_elasticity: number;
    /** Player stamina jump drain */
    plr_stamina_jump_drain: number;
    /** Whether shot location is shown in death view */
    plr_death_view_shot_location: boolean;
    /** Player max arm stamina */
    plr_max_arm_stamina: number;
    /** enables the recommended attachment system in the editor */
    dbg_enable_editor_recommended: boolean;
    /** Player vault barrier throw multiplier. Set dbg_vault_lines to true before playing with these values! */
    plr_vault_barrier_throw_multiplier: number;
    /** Player vault minimum vault animation time */
    plr_vault_min_vault_time: number;
    /** Spare rounds for internal-magazine weapons */
    plr_spare_rounds: number;
    /** Base size */
    cfg_smoke_puff_base_size: number;
    /** Whether the second utility slot is disabled */
    plr_disable_second_utility: boolean;
    /** debugger for aimmarker positioning error */
    dbg_optics: boolean;
    /** Player shove limb damage */
    plr_shove_limb_damage: number;
    /** How often chat tips are shown */
    chat_tip_frequency: number;
    /** Global recoil multiplier */
    plr_recoil: number;
    /** Maximum opacity of smoke puffs */
    cfg_smoke_max_opacity: number;
    /** Player shove torso damage */
    plr_shove_torso_damage: number;
    /** Whether movement anticheat is enabled */
    ac_movement: boolean;
    /** Player buck barrel deviation */
    plr_buck_barrel_deviation: number;
    /** How long the ping has to be over plr_ping_limit_sec for the client to get kicked */
    plr_ping_timeout_sec: number;
    /** Player initial health */
    plr_initial_health: number;
    /** whether to regen weapon offsets at runtime */
    dbg_position_runtime_regen: boolean;
    /** Whether chat tips are enabled */
    chat_tips_enabled: boolean;
    /** Whether mounting is enabled */
    plr_enable_mounting: boolean;
    /** Whether spawning is enabled in push */
    gm_push_spawning: boolean;
    /** Curl noise amplitude for smoke movement */
    cfg_smoke_curl_amplitude: number;
    /** whether rigging mode is enabled */
    dbg_prepare_for_rig: boolean;
    /** Player explosion blast pressure */
    plr_explosion_blast_pressure: number;
    /** Player movement stiffness at minimum weight */
    plr_movement_min_stiffness: number;
    /** Whether moderator tag in chat is disabled */
    sv_hide_mod_tag: boolean;
    /** Server replication frequency in hertz */
    gm_replication_frequency_hz: number;
    /** debugger in the editor */
    dbg_editor_debugger: boolean;
    /** Player health regen speed */
    plr_health_regen_sec: number;
    /** Whether players are forced to spawn in push */
    gm_push_force_spawning: boolean;
    /** Player vault top check max hits. Set dbg_vault_lines to true before playing with these values! */
    plr_vault_top_check_max_hits: number;
    /** Whether attachment streaming on-demand is enabled */
    ff_attachment_streaming: boolean;
    /** Player shove bayonet distance */
    plr_shove_bayonet_distance: number;
    /** Delay before the player dies after resetting */
    plr_reset_delay: number;
    /** Player replication frequency in hz */
    plr_replication_frequency_hz: number;
    /** Game version */
    readonly game_version: string;
    /** Random lifetime variance for smoke puffs */
    cfg_smoke_lifetime_variance: number;
    /** Whether lens flare is enabled */
    plr_lens_flare: boolean;
    /** Player shove melee torso damage */
    plr_shove_melee_torso_damage: number;
    /** Whether the magcheck UI shows exact ammo */
    plr_show_exact_magcheck_ammo: boolean;
    /** Player ragdoll throw strength */
    plr_ragdoll_strength: number;
    /** Player replication rollback time in milliseconds */
    plr_replication_rollback_time_ms: number;
    /** Physics throw force for voxel parts */
    voxel_throw_force: number;
    /** Projectile penetration multiplier */
    plr_penetration_multiplier: number;
    /** Default density of voronoi chunks for voxel destruction */
    voxel_default_voronoi_density: number;
    /** Player shove melee limb damage */
    plr_shove_melee_limb_damage: number;
    /** Player model. values include main, orchids_pbr_set, orchids_shark_set */
    plr_model: string;
    /** whether lighting will update according to lighting preset and time */
    dbg_disable_weather: boolean;
    /** Player max stamina */
    plr_max_stamina: number;
    /** Divisor for remote player move speed in equipment loop volume */
    cfg_equip_loop_remote_move_div: number;
    /** Smoothing speed for remote player equipment loop volume */
    cfg_equip_loop_remote_smooth: number;
    /** Whether modfiles are enabled */
    sv_modfiles_enabled: boolean;
    /** Whether additional error info exists */
    dbg_catch_errors: boolean;
    /** Game branch */
    readonly game_branch: string;
    /** Player damage multiplier */
    plr_damage_multiplier: number;
    /** Whether progression related buying features and limits are enabled */
    ro_earnings_enabled: boolean;
    /** Player jump recovery time in seconds */
    plr_jump_recovery: number;
    /** whether to show raycast shot trajectory */
    dbg_show_shot_trajectory: boolean;
    /** enables customizing the ammo positions in the editor */
    dbg_mag_stack: boolean;
    /** Player jump multiplier */
    plr_jump_multiplier: number;
    /** whether to show node offset debug ui in builder */
    dbg_debug_node_offsets: boolean;
    /** Player jump frequency in hz */
    plr_jump_frequency: number;
    /** Whether you can switch directions while in the air */
    plr_jump_control_momentum: boolean;
    /** Whether you can mount any attachment in any attachment slot. Allows for very scuffed gun builds */
    editor_mount_anything: boolean;
    /** Player ergonomics multiplier */
    plr_ergonomics_multiplier: number;
    /** Default NVG DOF focus distance */
    plr_default_nvg_dof_distance: number;
    /** How long to wait before capturing a point in other gamemodes */
    gm_time_to_capture: number;
    /** logservice screen output */
    dbg_logservice: boolean;
    /** Drum magazines available when spawning for drums */
    plr_drum_magazines: number;
    /** Grenade physics density */
    plr_grenade_density: number;
    /** Whether analytics are enabled */
    api_analytics_enabled: boolean;
    /** Whether spawning is enabled */
    sv_spawning_enabled: boolean;
    /** Player arm stamina drain while holding breath */
    plr_arm_stamina_drain_hold_breath: number;
    /** hold to interact time for magchecking and firemode checking */
    dbg_game_hold_to_interact_time: number;
    /** Player stamina lean drain */
    plr_stamina_lean_drain: number;
    /** Spare rounds for single-shot weapons */
    plr_single_shot_spare_rounds: number;
    /** Spatial frequency of curl noise for smoke */
    cfg_smoke_curl_frequency: number;
    /** Player stamina regen speed */
    plr_stamina_regen: number;
    /** Whether leaderboard markers are enabled */
    plr_enable_leaderboard_points: boolean;
    /** How much wind affects smoke movement */
    cfg_smoke_wind_factor: number;
    /** Whether NVG is disabled */
    plr_disable_nvg: boolean;
    /** Whether the magcheck UI is always shown */
    plr_always_show_magcheck: boolean;
    /** Magazines available when spawning for non-drum weapons */
    plr_magazines: number;
    /** Debounce before you can cancel a reload again */
    plr_cancel_reload_timeout: number;
    /** Player base weight */
    plr_base_weight: number;
    /** Player arm stamina regen speed */
    plr_arm_stamina_regen: number;
    /** Whether the server is shutting down */
    crit_shutdown: boolean;
    /** whether stats previews are disabled in the editor */
    dbg_editor_disable_stat_previews: boolean;
    /** Player arm stamina regen speed while crouching */
    plr_arm_stamina_regen_crouch: number;
    /** Whether fall damage is enabled */
    plr_fall_damage: boolean;
    /** Player arm stamina drain */
    plr_arm_stamina_drain: number;
    /** Divisor for local player move speed in equipment loop volume */
    cfg_equip_loop_move_div: number;
    /** How long a TDM match lasts in minutes */
    gm_match_time_minutes: number;
    /** Default camera mode. values include Default, Freecam, TPerson */
    plr_default_camera_mode: string;
    /** whether the gunshot emitter test mode is enabled. Only works while joining */
    dbg_test_gunshot_emitter: boolean;
    /** Whether only preload list attachments are loaded */
    sv_load_only_preloaded_attachments: boolean;
    /** Player shove distance */
    plr_shove_distance: number;
    /** How long to wait before refilling ammo with the refill interactable */
    gm_refill_interactable_cooldown_time: number;
    /** Vertical scale of wind effect on smoke */
    cfg_smoke_wind_vertical_scale: number;
    /** Player shove bayonet headshot damage */
    plr_shove_bayonet_headshot_damage: number;
    /** Player hip height */
    plr_hipheight: number;
    /** Whether compatibility check limits are enabled */
    editor_compatibility_checks: boolean;
    /** whether vaulting debug is enabled */
    dbg_vault_lines: boolean;
    /** Whether to log rodux store changes */
    dbg_store_changes: boolean;
    /** Whether the deploy screen forcibly shows the main match buttons */
    dbg_force_main_branch_deploy_config: boolean;
    /** delay after dying before death screen */
    dbg_post_death_delay: number;
    /** When the match intermission ends, or nil if there is none */
    sv_intermission_finish: undefined;
    /** React debugging flag */
    dbg_react: boolean;
    /** Player grenade throw strength */
    plr_grenade_throw_strength: number;
    /** Player vault top detection length */
    plr_vault_top_detection_length: number;
    /** Smoke puffs emitted per second */
    cfg_smoke_emit_rate: number;
    /** Random speed variance for emitted smoke puffs */
    cfg_smoke_emit_speed_variance: number;
    /** Drag coefficient for smoke puffs */
    cfg_smoke_drag_coefficient: number;
    /** Player vault inward offset. Set dbg_vault_lines to true before playing with these values! */
    plr_vault_inward_offset: number;
    /** Player vault max vault animation time */
    plr_vault_max_vault_time: number;
}